name: Build Azure Function

on:
   push:
    branches:
      - main            

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet '8.0.x' Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './src/host/Web2ls.Functions'
        dotnet build --configuration Release
        popd
        
